server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: student_service
          uri: http://localhost:8080
          predicates:
            - Path=/students/**